spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#      lob:
#        non_contextual_creation: true
#      temp:
#        use_jdbc_metadata_defaults: false
#      current_session_context_class: thread
  datasource:
    platform: org.hibernate.dialect.PostgreSQL95Dialect
    url: jdbc:postgresql://127.0.0.1:5432/digitalzone_db?currentSchema=digitalzone
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver